package main

import (
	// "fmt"

	"context"

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
	_ "huynhmanh.com/gin/docs" // Docs auto-generated by swag init
	"huynhmanh.com/gin/internal/api/v1/routes"
	"huynhmanh.com/gin/internal/config"
)

// import "github.com/gin-gonic/gin"

func main() {
	cfg := config.LoadConfig()

	db := config.SetupDatabase(cfg.DBDSN)

	redisClient, err := config.InitRedis(context.Background(), cfg.RedisHost, cfg.RedisPort)
	if err != nil {
		panic(err)
	}
	defer config.CloseRedis(redisClient)

	logger := config.NewLogger()
	defer logger.Sync()

	if err := config.RunMigrations(db); err != nil {
		panic(err)
	}

	r := gin.Default()
	routes.RegisterUserRoutes(r, db, redisClient, logger)
	routes.RegisterProductRoutes(r,db,redisClient,logger)
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	r.Run(":3000")
}

// @title           User Management API
// @version         1.0.0
// @description     API for managing users, authentication, and profiles
// @termsOfService  http://example.com/terms/

// @contact.name   API Support
// @contact.url    http://example.com/support
// @contact.email  support@example.com

// @license.name  MIT
// @license.url   https://choosealicense.com/licenses/mit/

// @host      localhost:3000
// @BasePath  /api/v1

// @schemes http https
// @consumes application/json
// @produces application/json

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Type "Bearer" followed by a space and JWT token.
